### ISSUE TITLE
关于代码中力封闭的判断

### ISSUE THREAD

**Issue by Suyixiu** [Hymwgk/dex-net#1]
请问大佬Dex-net中判断是否力封闭难道是计算一下两个接触点连线与各自法线的夹角然后与摩擦系数的arctan值做一下比较吗？
根据你[代码](https://github.com/Hymwgk/dex-net/blob/master/src/dexnet/grasping/quality.py)中的注释理解的，不知道是不是这个样子
大佬可以加一下微信请教一些问题吗，可以有偿
我微信15218208681
万分感谢😃

**Comment by Hymwgk** [comment]
我的理解是这样的，力闭合的计算和《新版机器人技术手册 [日]日本机器人学会编 2007》上的定义是一样的，我记得网上有中文文档

**Comment by Suyixiu** [comment]
好的，谢谢
